# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Game.create(title: "Wild Arms 2", release_year: 1998, console:"Playstation", developer: "Media.Vision/Contrail", genre: "JRPG", description: "A western-themed tale, set in the land of Filgaia. You play as six strangers that form a team with the goal of saving the planet from disaster!", cover_art: "https://upload.wikimedia.org/wikipedia/en/8/8c/Wild_ARMs_2_Cover_Art.jpg")
Game.create(title: "Chrono Cross", release_year: 1999, console:"Playstation", developer: "Square-Enix", genre: "JRPG", description: "The story of Chrono Cross focuses on a teenage boy named Serge and a theme of parallel worlds. Faced with an alternate reality in which he died as a child, Serge endeavors to discover the truth of the two worlds' divergence.", cover_art:"https://upload.wikimedia.org/wikipedia/en/9/9a/Chronocrossbox.jpg")
Game.create(title: "Final Fantasy X", release_year: 2001, console:"Playstation 2", developer: "Square-Enix", genre: "JRPG", description: "Set in the fantasy world of Spira, the game's story revolves around a group of adventurers and their quest to defeat a rampaging monster known as Sin.", cover_art: "https://glitchwave.com/game/final-fantasy-x/#images,game_art,554,6849433")
Game.create(title: "Azure Dreams", release_year: 1997, console:"Playstation", developer: "Konami", genre: "Roguelike", description: "Azure Dreams is set in the desert town of Monsbaiya. The town prospers because of a Monster Tower located over it. A skilled monster tamer named Guy disappears in the tower and is never seen again. His son, Koh, enters the tower when he turns 15 and meets a familiar named Kewne - a monster that can speak to humans. Kewne and Koh embark on a quest to reach the top of the Monster Tower and find the truth about Guy's fate.", cover_art: "https://upload.wikimedia.org/wikipedia/en/7/78/Azure_Dreams_Coverart.png")